name: Deploy Apps Script

on:
  push:
    branches:
      - main
    paths:
      - 'appsscript/**'
      - '.github/workflows/appsscript-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Updated to latest LTS

      - name: Install dependencies
        working-directory: ./appsscript
        run: npm install

      - name: Create Auth Files
        shell: bash
        env:
          CLASP_CONFIG: ${{ secrets.CLASP_JSON }}
          CLASPRC_CONFIG: ${{ secrets.CLASPRC_JSON }}
        run: |
          # Write .clasp.json to the project directory
          echo "$CLASP_CONFIG" > ./appsscript/.clasp.json
          # Write .clasprc.json to the home directory
          echo "$CLASPRC_CONFIG" > ~/.clasprc.json

      - name: Push to Apps Script
        working-directory: ./appsscript
        run: npx @google/clasp push -f

      - name: Deploy Apps Script
        working-directory: ./appsscript
        run: npx @google/clasp deploy
